### ISSUE TITLE
Dans le programme compileAttributes 

### ISSUE THREAD

**Issue by scisseehcvm** [arthur-shaw/ehcvm-tri-automatique#10]
Programme compileAttributes.do
A la ligne 404 enlever le caractère "/" dans le chemin d'accès de la Base equipements
au lieu de "merge 1:m interview__id interview__key using "`rawDir'/`equipAgric'", nogen"
Mettre "merge 1:m interview__id interview__key using "`rawDir'`equipAgric'", nogen"

**Comment by arthur-shaw** [comment]
Samba, le chemin du fichier est bien formulé:

`merge 1:m interview__id interview__key using "`rawDir'/`equipAgric'", nogen`

Le problème réside plutôt dans le nom du fichier. Le programme s'attend à voir une base `equipements.dta` (selon le paramètre à la ligne 123 du programme `configurePrograms.do`). 

Lors de la première vague, certains avait un nom différent pour ce fichier. Lors de la présente vague, nous avons harmonisé les noms de base.

Comme l'ANSD teste avec les données de la première vague, il faut modifier soit les attentes du programme soit le nom des bases.

Pour modifier (temporairement) les attentes du programme, modifier les noms de base à partir de la ligne 114 du programme `configurePrograms.do`.

Pour modifier (temporairement), insérer à la ligne 123 du programme `runAll.do` une syntaxe comme suit pour modifier le nom des bases pour s'aligner avec les attentes du programme:

```
cd "`rawDir'/"
! rename ancienNom.dta nouveauNom.dta
```
En lieu et place de `ancienNom` et `nouveauNom`, mettre à `ancienNom` le nom de base telle qu'exporté  et à `nouveauNom` le nom selon les attentes du programmes.

Sur ce sujet, me contacter directement par Skype si tu as besoin d'un petit appui.
