### ISSUE TITLE
Erreur sur le nom de la base equipement dans le programme configurePrograms.do

### ISSUE THREAD

**Issue by scisseehcvm** [arthur-shaw/ehcvm-tri-automatique#11]
Dans le programme configurePrograms.do 
1. Changer le nom de la base "equipements" en "equipments" car il n'y a pas de "e" entre le "p" et le "m" à l'exportation  de cette base.

**Comment by arthur-shaw** [comment]
Voir #10 et la liste de corrections des noms de base à partir de la ligne 12 [ici](https://docs.google.com/spreadsheets/d/1_QL5qDpA5EXSO2_iupEcgRLA7QHH8hOf9ZjoH1bMcSQ/edit?usp=sharing)
